language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  # package requirements
  - pip install -r requirements.txt
  # linting tests
  - pip install flake8
  - pip install pylint
  - pip install pydocstyle

script:
  # linting tests
  - flake8 --config=.flake8 geizhalscrawler/
  - pylint --disable=R0903 geizhalscrawler/
  - pydocstyle geizhalscrawler/
  # run unit tests
  - python -m unittest discover tests "*.py"

#notifications:
#  email:
#    on_success: never
#    on_failure: change

#deploy:
#  provider: pypi
#  user: juka
#  password:
#    secure: gOBoqOp89wxXAbHayWFMt7kuOe2pTFKC3vIqXFacPRQuqVzZEi7/xwtUVfc5pJh3BQuHnFd5MXQblxmotF0vd6aIZoGBQLNmTaUbFDbrCho+2fLZH0hRV/xSDsuUQ6mMxe8m5dTpeQ+lKs3yESzP1i0yVn/LifMsrSIqM83krbp/tBFPt6gke2/SxoJSSxjDzkWy22p+bT09PnmgvgGYusAKIzCVqCrM6UCQDQxpgiIECYd9LzND/fy1oSscc620VvJlQ9M5kMYrHY2YPC4H2HXFWcKGdMuQuazx3Fv99ovcQ9p2+yeP8+u0BThusNIaHXkf9BzWzNZGXj/iorBJPl+pt/ulVWRM74a/gxRNSSwzvjemD3VrOaJsQNJmIDTwQBvyy+rx6jxgvVYIQK/1IKS5GsfbdsU9afHk55+FiRhyM7dZu9c2YfmROqTHgHrae6QALcd8fYSLWFtGwm3C87e92iJrXZrsNEhX31fxLDlRgVXTtJuN6dIY5ZJW4J+23gX4Ed7hQkY+e7CdVjZByKGH/uX2m1yIlT+kSAkl0utJPBNTJ1PtQrBnJM7x4aihkg8/7/vN66kbdahf3cBxNVDs6o7mpCaOizgavJzjdei3917lO17t/KHA/g1s+6cPvth+ZfAoti09LWH6tcpIJuoop/vG59tvLixBBXTVHts=
#  on:
#    tags: true
#    condition: $TRAVIS_PYTHON_VERSION = 3.6
